### ISSUE TITLE
Update documentation to provide instructions when using self-signed certificates

### ISSUE THREAD

**Issue by millerjp** [axonops/documentation#29]
eg
```
tls:
  mode: "TLS"
  skipVerify: true # Disables host and CA verification, not sure if you want/need this?
  caFile: "/path/to/ca.crt" # required if skipVerify is not set and you are using a self-signed cert
```

vs 
```
# SSL/TLS Settings
tls:
  mode: "disabled" # disabled, TLS
  # Only set if mode is TLS
  skipVerify: false
  caFile: "path_to_certs_on_cassandra_node.crt"
  certFile: "path_to_certs_on_cassandra_node.crt"
  keyFile: "path_to_key_file_on_cassandra_node.key"
```
